name: ItemStock
main: com.jackyyf.ItemStock.ItemStock
version: 0.0.1 Alpha
commands:
  is:
    description: Command for ItemStock
    usage: Type "/is help" for usage

permissions:
  is.*:
    description: All access to this plugin.
    children:
      is.getUsers: true
      is.getStocks: true
      is.admin: true
  is.getUsers:
    description: Allows player to get users from remote server.
    default: op
  is.getStocks:
    description: Allows player to get active stocks from remote server.
    default: true
  is.admin:
    description: Allows player to take full access to this plugin. (Get server status, disable/enable plugin, etc)
    default: op